---
--- Generated by Luanalysis
--- Created by xuhaidong.
--- DateTime: 2023/8/28 22:20
---
local val = redis.call("get",KEYS[1])
if not val then
    --key不存在
    return redis.call("set",KEYS[1],ARGV[1],'EX',ARGV[2])
elseif val == ARGV[1] then
    --上一次加锁成功 则重设过期时间
    redis.call("expire",KEYS[1],ARGV[2])
    return "OK"
else
    --别人持有锁
    return ""
end
