---
--- Generated by Luanalysis
--- Created by xuhaidong.
--- DateTime: 2023/8/28 20:52
---
---检查是不是自己的锁，是的话就续约，不是的话返回错误
if redis.call("get",KEYS[1]) == ARGV[1] then
    return redis.call("expire", KEYS[1], ARGV[2])
else
    return 0
end